{-# OPTIONS_GHC -fno-warn-missing-signatures #-}
module QCommon.CVarVariables where

import           Control.Lens      (use)
import qualified Data.ByteString   as B
import qualified Data.HashMap.Lazy as HM
import           Data.Maybe        (fromMaybe)

import           QuakeState
import           Types

getExisting :: B.ByteString -> Quake CVarT
getExisting = fmap (fromMaybe (error "CVar.getExisting returned Nothing")) . findVar

-- TODO: this is a duplicate from QCommon.CVar in order to avoid cyclic dependency (is it ok like that?)
findVar :: B.ByteString -> Quake (Maybe CVarT)
findVar name =
  do vars <- use (globals.gCVars)
     return (HM.lookup name vars)

clStereoSeparationCVar       = getExisting "cl_stereo_separation"
clStereoCVar                 = getExisting "cl_stereo"
clAddBlendCVar               = getExisting "cl_blend"
clAddLightsCVar              = getExisting "cl_lights"
clAddParticlesCVar           = getExisting "cl_particles"
clAddEntitiesCVar            = getExisting "cl_entities"
clGunCVar                    = getExisting "cl_gun"
clFootstepsCVar              = getExisting "cl_footsteps"
clNoSkinsCVar                = getExisting "cl_noskins"
clAutoSkinsCVar              = getExisting "cl_autoskins"
clPredictCVar                = getExisting "cl_predict"
clMaxFPSCVar                 = getExisting "cl_maxfps"
clUpSpeedCVar                = getExisting "cl_upspeed"
clForwardSpeedCVar           = getExisting "cl_forwardspeed"
clSideSpeedCVar              = getExisting "cl_sidespeed"
clYawSpeedCVar               = getExisting "cl_yawspeed"
clPitchSpeedCVar             = getExisting "cl_pitchspeed"
clAngleSpeedkeyCVar          = getExisting "cl_anglespeedkey"
clRunCVar                    = getExisting "cl_run"
lookSpringCVar               = getExisting "lookspring"
lookStrafeCVar               = getExisting "lookstrafe"
mPitchCVar                   = getExisting "m_pitch"
mYawCVar                     = getExisting "m_yaw"
mForwardCVar                 = getExisting "m_forward"
mSideCVar                    = getExisting "m_side"
clShowNetCVar                = getExisting "cl_shownet"
clShowMissCVar               = getExisting "cl_showmiss"
clTimeoutCVar                = getExisting "cl_timeout"
showClampCVar                = getExisting "showclamp"
timeDemoCVar                 = getExisting "timedemo"
pausedCVar                   = getExisting "paused"
rconClientPasswordCVar       = getExisting "rcon_password"
rconAddressCVar              = getExisting "rcon_address"
clLightLevelCVar             = getExisting "r_lightlevel"
infoPasswordCVar             = getExisting "password"
infoSpectatorCVar            = getExisting "spectator"
nameCVar                     = getExisting "name"
skinCVar                     = getExisting "skin"
rateCVar                     = getExisting "rate"
msgCVar                      = getExisting "msg"
handCVar                     = getExisting "hand"
fovCVar                      = getExisting "fov"
genderCVar                   = getExisting "gender"
clVwepCVar                   = getExisting "cl_vwep"
conNotifyTimeCVar            = getExisting "con_notifytime"
noStdoutCVar                 = getExisting "nostdout"
hostSpeedsCVar               = getExisting "host_speeds"
logStatsCVar                 = getExisting "log_stats"
developerCVar                = getExisting "developer"
timeScaleCVar                = getExisting "timescale"
fixedTimeCVar                = getExisting "fixedtime"
logfileActiveCVar            = getExisting "logfile"
showTraceCVar                = getExisting "showtrace"
dedicatedCVar                = getExisting "dedicated"
mFilterCVar                  = getExisting "m_filter"
inMouseCVar                  = getExisting "in_mouse"
freeLookCVar                 = getExisting "freelook"
sensitivityCVar              = getExisting "sensitivity"
maxClientsCVar               = getExisting "maxclients"
hostnameCVar                 = getExisting "hostname"
timeoutCVar                  = getExisting "timeout"
zombieTimeCVar               = getExisting "zombietime"
svEnforceTimeCVar            = getExisting "sv_enforcetime"
allowDownloadCVar            = getExisting "allow_download"
allowDownloadPlayersCVar     = getExisting "allow_download_players"
allowDownloadModelsCVar      = getExisting "allow_download_models"
allowDownloadSoundsCVar      = getExisting "allow_download_sounds"
allowDownloadMapsCVar        = getExisting "allow_download_maps"
svNoReloadCVar               = getExisting "sv_noreload"
svAirAccelerateCVar          = getExisting "sv_airaccelerate"
publicServerCVar             = getExisting "public"
svReconnectLimitCVar         = getExisting "sv_reconnect_limit"
fsBaseDirCVar                = getExisting "basedir"
fsCdDirCVar                  = getExisting "cddir"
fsGameDirVarCVar             = getExisting "game"
maxEntitiesCVar              = getExisting "maxentities"
mapNoAreasCVar               = getExisting "map_noareas"
skillCVar                    = getExisting "skill"
coopCVar                     = getExisting "coop"
deathmatchCVar               = getExisting "deathmatch"
dmFlagsCVar                  = getExisting "dmflags"
svMaxVelocityCVar            = getExisting "sv_maxvelocity"
svRollAngleCVar              = getExisting "sv_rollangle"
svRollSpeedCVar              = getExisting "sv_rollspeed"
svGravityCVar                = getExisting "sv_gravity"
timeLimitCVar                = getExisting "timelimit"
fragLimitCVar                = getExisting "fraglimit"
spectatorPasswordCVar        = getExisting "spectator_password"
vidWidthCVar                 = getExisting "vid_width"
vidHeightCVar                = getExisting "vid_height"
vidRefCVar                   = getExisting "vid_ref"
vidFullScreenCVar            = getExisting "vid_fullscreen"
vidXPosCVar                  = getExisting "vid_xpos"
vidYPosCVar                  = getExisting "vid_ypos"
vidGammaCVar                 = getExisting "vid_gamma"
glModeCVar                   = getExisting "gl_mode"
glPicMipCVar                 = getExisting "gl_picmip"
glExtPalettedTextureCVar     = getExisting "gl_ext_palettedtexture"
glSwapIntervalCVar           = getExisting "gl_swapinterval"
glMonoLightMapCVar           = getExisting "gl_monolightmap"
gl3DLabsBrokenCVar           = getExisting "gl_3dlabs_broken"
glExtCompiledVertexArrayCVar = getExisting "gl_ext_compiled_vertex_array"
glExtPointParametersCVar     = getExisting "gl_ext_pointparameters"
glExtMultiTextureCVar        = getExisting "gl_ext_multitexture"
glTextureModeCVar            = getExisting "gl_texturemode"
glTextureAlphaModeCVar       = getExisting "gl_texturealphamode"
glTextureSolidModeCVar       = getExisting "gl_texturesolidmode"
glParticleAttACVar           = getExisting "gl_particle_att_a"
glParticleAttBCVar           = getExisting "gl_particle_att_b"
glParticleAttCCVar           = getExisting "gl_particle_att_c"
glParticleMinSizeCVar        = getExisting "gl_particle_min_size"
glParticleMaxSizeCVar        = getExisting "gl_particle_max_size"
glNoBindCVar                 = getExisting "gl_nobind"
glRoundDownCVar              = getExisting "gl_round_down"
glLogCVar                    = getExisting "gl_log"
glDrawBufferCVar             = getExisting "gl_drawbuffer"
glZTrickCVar                 = getExisting "gl_ztrick"
glClearCVar                  = getExisting "gl_clear"
glSkyMipCVar                 = getExisting "gl_skymip"
glFinishCVar                 = getExisting "gl_finish"
glFlashBlendCVar             = getExisting "gl_flashblend"
glCullCVar                   = getExisting "gl_cull"
glLightMapCVar               = getExisting "gl_lightmap"
glShowTrisCVar               = getExisting "gl_showtris"
glDynamicCVar                = getExisting "gl_dynamic"
glModulateCVar               = getExisting "gl_modulate"
glShadowsCVar                = getExisting "gl_shadows"
glPolyBlendCVar              = getExisting "gl_polyblend"
glDriverCVar                 = getExisting "gl_driver"
intensityCVar                = getExisting "intensity"
viewSizeCVar                 = getExisting "viewsize"
clNoDeltaCVar                = getExisting "cl_nodelta"
clTestParticlesCVar          = getExisting "cl_testparticles"
clTestEntitiesCVar           = getExisting "cl_testentities"
clTestLightsCVar             = getExisting "cl_testlights"
clTestBlendCVar              = getExisting "cl_testblend"
clStatsCVar                  = getExisting "cl_stats"
fpsCVar                      = getExisting "fps"
scrDrawAllCVar               = getExisting "scr_drawall"
scrShowPauseCVar             = getExisting "scr_showpause"
scrConSpeedCVar              = getExisting "scr_conspeed"
qportCVar                    = getExisting "qport"
showPacketsCVar              = getExisting "showpackets"
showDropCVar                 = getExisting "showdrop"
scrDebugGraphCVar            = getExisting "debuggraph"
scrTimeGraphCVar             = getExisting "timegraph"
crosshairCVar                = getExisting "crosshair"
runRollCVar                  = getExisting "run_roll"
runPitchCVar                 = getExisting "run_pitch"
bobPitchCVar                 = getExisting "bob_pitch"
bobRollCVar                  = getExisting "bob_roll"
bobUpCVar                    = getExisting "bob_up"
gunXCVar                     = getExisting "gun_x"
gunYCVar                     = getExisting "gun_y"
gunZCVar                     = getExisting "gun_z"
noRefreshCVar                = getExisting "r_norefresh"
speedsCVar                   = getExisting "r_speeds"
noVisCVar                    = getExisting "r_novis"
drawWorldCVar                = getExisting "r_drawworld"
noCullCVar                   = getExisting "r_nocull"
drawEntitiesCVar             = getExisting "r_drawentities"
lerpModelsCVar               = getExisting "r_lerpmodels"
scrCenterTimeCVar            = getExisting "scr_centertime"
gSelectEmptyCVar             = getExisting "g_select_empty"
genderAutoCVar               = getExisting "gender_auto"
maxSpectatorsCVar            = getExisting "maxspectators"